---
driver:
  name: vagrant
  customize:
    memory: 3000
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04

suites: 
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[apt::install]
      - recipe[streamingExperiment::install]
      - recipe[streamingExperiment::experiment]
      - recipe[streamingExperiment::setup]
      - recipe[streamingExperiment::testFlink]
      - recipe[streamingExperiment::testSpark]

    attributes:
         streamingExperiment:
            experiment:
                private_ips: ["10.0.2.15"]
                public_ips: ["10.0.2.15"]
            setup:
              private_ips: ["10.0.2.15"]
              public_ips: ["10.0.2.15"]
            testFlink:
              private_ips: ["10.0.2.15"]
              public_ips: ["10.0.2.15"]
            testSpark:
              private_ips: ["10.0.2.15"]
              public_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         apt:    
	          private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"

